ALTER TABLE  TB_REVIEW 
ADD CONSTRAINT FK_TB_REVIEW_TB_FACILITY FOREIGN KEY(시설번호) REFERENCES TB_FACILITY(시설번호);
ALTER TABLE  TB_REVIEW 
ADD CONSTRAINT FK_TB_REVIEW_TB_MEMBER FOREIGN KEY(아이디) REFERENCES TB_MEMBER(아이디);
ALTER TABLE  TB_REVIEW 
ADD CONSTRAINT FK_TB_REVIEW_TB_FILE FOREIGN KEY(파일번호) REFERENCES TB_FILE(파일번호);

ALTER TABLE  TB_COMMUNITY 
ADD CONSTRAINT FK_TB_COMMUNITY_TB_MEMBER FOREIGN KEY(아이디) REFERENCES TB_MEMBER(아이디);
ALTER TABLE  TB_COMMUNITY 
ADD CONSTRAINT FK_TB_COMMUNITY_TB_FILE FOREIGN KEY(파일번호) REFERENCES TB_FILE(파일번호);

ALTER TABLE  TB_COMMENT 
ADD CONSTRAINT FK_TB_COMMENT_TB_COMMUNITY FOREIGN KEY(글번호) REFERENCES TB_COMMUNITY(글번호);
ALTER TABLE  TB_COMMENT 
ADD CONSTRAINT FK_TB_COMMENT_TB_MEMBER FOREIGN KEY(아이디) REFERENCES TB_MEMBER(아이디);

ALTER TABLE  TB_REVIEW_COMMENT 
ADD CONSTRAINT FK_TB_RECOMMENT_TB_COMMUNITY FOREIGN KEY(리뷰번호) REFERENCES TB_REVIEW(리뷰번호);
ALTER TABLE  TB_REVIEW_COMMENT 
ADD CONSTRAINT FK_TB_RECOMMENT_TB_MEMBER FOREIGN KEY(아이디) REFERENCES TB_MEMBER(아이디);




















ALTER TABLE TB_COMMUNITY ADD 좋아요 NUMBER;
ALTER TABLE TB_COMMUNITY ADD 조회수 NUMBER;
ALTER TABLE TB_REVIEW ADD 좋아요 NUMBER;
ALTER TABLE TB_REVIEW ADD 조회수 NUMBER;
ALTER TABLE TB_COMMENT ADD 좋아요 NUMBER;
ALTER TABLE TB_REVIEW_COMMENT ADD 좋아요 NUMBER;
ALTER TABLE TB_REVIEW ADD 리뷰평점 NUMBER;



DROP TABLE TB_REVIEW;
DROP TABLE TB_FACILITY;
DROP TABLE TB_COMMUNITY;
DROP TABLE TB_COMMENT;
DROP TABLE TB_FILE;
DROP TABLE TB_MEMBER;


DROP TABLE MEMBER;

CREATE TABLE TB_FACILITY (
      시설번호  NUMBER   PRIMARY KEY
    , 시설이름  VARCHAR2(100)    
    , 구분     VARCHAR2(100) 
    , 주요시설  VARCHAR2(100)
    , 영업시간  VARCHAR2(100)
    
    , 전화번호  VARCHAR2(100)
    , 가격     VARCHAR2(100)
    , 결제방법  VARCHAR2(100)
    , 편의시설  VARCHAR2(100)
    , 홈페이지  VARCHAR2(100)
    
    , 태그     VARCHAR2(100)
    , 설명    VARCHAR2(2000)
    , 설치년도  VARCHAR2(100)  
    , 면적     NUMBER
    , 주소    VARCHAR2(100)
    
    , X좌표   NUMBER
    , Y좌표   NUMBER
    , 등록일자  DATE
);

CREATE SEQUENCE FACILITY_NUM START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE REVIEW_NUM START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FILE_NUM START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE COMMUNITY_NUM START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE COMMENT_NUM START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE REVIEW_COMMENT_NUM START WITH 1 INCREMENT BY 1;



DROP SEQUENCE FACILITY_NUM;

DESC TB_MEMBER;
DESC TB_FILE;
DESC TB_REVIEW;
DESC TB_COMMENT;
DESC TB_COMMUNITY;
INSERT INTO TB_FACILITY (시설번호, 등록일자) VALUES (FACILITY_NUM.NEXTVAL,SYSDATE);
INSERT INTO TB_MEMBER VALUES ('TEST5', '비밀번호', '이름', 20, '01012341234', '운동경력', '주소',0,SYSDATE );
INSERT INTO TB_FILE VALUES (FILE_NUM.NEXTVAL, '파일이름', '파일실제이름', 0, 'Y', SYSDATE );
INSERT INTO TB_REVIEW VALUES (REVIEW_NUM.NEXTVAL, '리뷰제목', '리뷰내용', 1, 'TEST1',1, SYSDATE, 0, 0);
INSERT INTO TB_COMMUNITY VALUES (COMMUNITY_NUM.NEXTVAL, '글제목', '글내용',1, 'TEST1', SYSDATE);
INSERT INTO TB_COMMENT VALUES (COMMENT_NUM.NEXTVAL, '댓글제목', '댓글내용','TEST1', 1, SYSDATE);
INSERT INTO TB_REVIEW_COMMENT VALUES (REVIEW_COMMENT_NUM.NEXTVAL, '댓글제목', '댓글내용','TEST1', 1, SYSDATE);

select * from tb_file;
select * FROM TB_MEMBER;
select * from tb_review;
select * from tb_facility;
select * from tb_review_comment;
desc tb_comment;
desc tb_review_comment;
select * from tb_review_comment;

SELECT SESSIONTIMEZONE FROM dual;
SELECT DBTIMEZONE FROM dual;








CREATE TABLE TB_REVIEW(
    리뷰번호 NUMBER PRIMARY KEY,
    리뷰제목 VARCHAR2(100) NOT NULL,
    리뷰내용 VARCHAR2(3900) NOT NULL,
    시설번호 NUMBER NOT NULL,
    아이디 VARCHAR2(50) NOT NULL,
    파일번호 NUMBER ,
    등록일자 DATE  
);

CREATE TABLE TB_MEMBER(
    아이디 VARCHAR2(20) PRIMARY KEY,
    비밀번호 VARCHAR2(20) NOT NULL,
    이름 VARCHAR2(20) NOT NULL,
    나이 NUMBER,
    연락처 VARCHAR2(20),
    운동경력 VARCHAR2(20),
    주소 VARCHAR2(20) NOT NULL,
    포인트 NUMBER,
    등록일자 DATE
);

CREATE TABLE TB_COMMUNITY(
    글번호 NUMBER PRIMARY KEY,
    글제목 VARCHAR2(100) NOT NULL,
    글내용 VARCHAR2(2000) NOT NULL,
    파일번호 NUMBER,
    아이디 VARCHAR2(50) NOT NULL,
    댓글번호 NUMBER NOT NULL,
    등록일자 DATE
);

CREATE TABLE TB_COMMENT(
    댓글번호 NUMBER PRIMARY KEY,
    댓글제목 VARCHAR2(100) NOT NULL,
    댓글내용 VARCHAR2(2000) NOT NULL,
    아이디 VARCHAR2(20) NOT NULL,
    글번호 NUMBER NOT NULL, 
    등록일자 DATE
);

CREATE TABLE TB_REVIEW_COMMENT(
    댓글번호 NUMBER PRIMARY KEY,
    댓글제목 VARCHAR2(100) NOT NULL,
    댓글내용 VARCHAR2(2000) NOT NULL,
    아이디 VARCHAR2(20) NOT NULL,
    리뷰번호 NUMBER NOT NULL, 
    등록일자 DATE
);



CREATE TABLE TB_FILE(
    파일번호 NUMBER PRIMARY KEY,
    파일이름 VARCHAR2(1000),
    파일실제이름 VARCHAR2(1000),
    다운로드횟수  NUMBER,
    영수증유무 VARCHAR2(1) CHECK(영수증유무 IN ('Y','N')),
    등록일자 DATE
);



SELECT * FROM TB_COMMUNITY;

DROP TABLE TB_COMMENT;
DROP TABLE TB_COMMUNITY;
DROP TABLE TB_FILE;

DROP TABLE TB_FACILITY;
DROP TABLE TB_MEMBER;
DROP TABLE MEMBER;








CREATE TABLE TB_COMMENT(
    댓글번호 NUMBER PRIMARY KEY,
    댓글제목 VARCHAR2(100) NOT NULL,
    댓글내용 VARCHAR2(1000) NOT NULL,
    작성자 VARCHAR2(50) NOT NULL,
    작성일자 DATE
);

CREATE TABLE TB_COMMUNITY(
    글번호 NUMBER PRIMARY KEY,
    글제목 VARCHAR2(100) NOT NULL,
    글내용 VARCHAR2(2000) NOT NULL,
    작성자 VARCHAR2(50) NOT NULL,
    작성일자 DATE
);






SELECT * FROM TB_FACILITY;
SELECT * FROM TB_REVIEW;
SELECT * FROM TB_REVIEW_COMMENT;
SELECT * FROM TB_COMMUNITY;
SELECT * FROM TB_COMMENT;



COMMIT;

